- project:
    name: RCP
    module:
      - SS_HAProxy:
          scmurl: scm_rcp
      - SS_ILDBHAforPostgres:
          scmurl: scm_il
      - SS_ILDeployment:
          scmurl: scm_il
      - SS_ILDBM:
          scmurl: scm_il
      - SS_ILPGSProxyLib:
          scmurl: scm_il
      - SS_ILPostgres:
          scmurl: scm_il
      - SS_ILPostgresClient:
          scmurl: scm_il
      - SS_QNDPM:
          scmurl: scm_il
      - SS_RCPMsg:
          scmurl: scm_rcp
      - SS_RCPMsgLib:
          scmurl: scm_rcp
      - SS_RCPHAproxyMGMT:
          scmurl: scm_rcp
      - SS_RCPNTP:
          scmurl: scm_rcp
      - SS_TestRCPNTP:
          scmurl: scm_rcp
      - SS_ZMQLib:
          scmurl: scm_rcp
      
    jobs:
      - '{module}'
      - '{module}_COMPILE'
      - '{module}_UT'
      - '{module}_STATIC_ANALYSIS'
      - '{module}_IMAGE_PATCH_UPLOAD'
      - '{module}_FT'

- job-template:
    name: '{module}'
    project-type: flow
    dsl: |
        parallel (
            {{ build("{module}_COMPILE",GERRIT_SCHEME:params["GERRIT_SCHEME"],GERRIT_HOST:params["GERRIT_HOST"],GERRIT_PORT:params["GERRIT_PORT"],GERRIT_PROJECT:params["GERRIT_PROJECT"],GERRIT_BRANCH:params["GERRIT_BRANCH"],GERRIT_REFSPEC:params["GERRIT_REFSPEC"],parent_buildnum:build.number) }},
            {{ build("{module}_STATIC_ANALYSIS",GERRIT_SCHEME:params["GERRIT_SCHEME"],GERRIT_HOST:params["GERRIT_HOST"],GERRIT_PORT:params["GERRIT_PORT"],GERRIT_PROJECT:params["GERRIT_PROJECT"],GERRIT_BRANCH:params["GERRIT_BRANCH"],GERRIT_REFSPEC:params["GERRIT_REFSPEC"]) }}
            {{ build("{module}_UT",GERRIT_SCHEME:params["GERRIT_SCHEME"],GERRIT_HOST:params["GERRIT_HOST"],GERRIT_PORT:params["GERRIT_PORT"],GERRIT_PROJECT:params["GERRIT_PROJECT"],GERRIT_BRANCH:params["GERRIT_BRANCH"],GERRIT_REFSPEC:params["GERRIT_REFSPEC"]) }}
        )
        build("{module}_image_patch_upload",target_image_name:params["GERRIT_REFSPEC"],parent_buildnum:build.number)
        build("{module}_FT",DELIVERY_NAME:params["GERRIT_REFSPEC"])
    triggers:
      - RCP_TRIGGER:
          subsystem: '{module}'
          scmurl: '{scmurl}'

- job-template:
    name: '{module}_COMPILE'
    node: docker_image
    parameters: 
      - COMPILE_PARA:
          subsystem: '{module}'
    project-type: freestyle
    wrappers: 
      - RCP_WRAPPERS
    builders: 
      - COMPILE_builder
    publishers:
      - COMPILE_ARTIFACT:
          subsystem: '{module}'

- job-template:
    name: '{module}_STATIC_ANALYSIS'
    node: docker_image
    parameters:
      - COMPILE_PARA:
          subsystem: '{module}'
    project-type: freestyle
    wrappers: 
      - RCP_WRAPPERS
    builders: 
      - STATISTIC_builder
    publishers:
      - STATIC_ARTIFACT

- job-template:
    name: '{module}_UT'
    node: docker_image
    parameters:
      - COMPILE_PARA:
          subsystem: '{module}'
    project-type: freestyle
    wrappers: 
      - RCP_WRAPPERS
    builders: 
      - UT_builder
    publishers:
      - UT_ARTIFACT
      
- job-template:
    name: '{module}_IMAGE_PATCH_UPLOAD'
    node: fedora20
    parameters:
      !include image_upload_args.yaml.inc
    project-type: freestyle
    wrappers:
      - RCP_WRAPPERS
    builders:
      - UPLOAD_IMAGE_builder:
    publishers:
      - UPLOAD_IMAGE_ARTIFACT:

- job-template:
    name: '{module}_FT'
    node: rcpft
    parameters:
      !include rcpargs.yaml.inc
    project-type: freestyle     
    wrappers:
      - RCP_WRAPPERS
    builders:
      - FT_builder:
    publishers:
      - FT-ARTIFACT

- parameter:
    name: COMPILE_PARA
    parameters:
      - string:
          name: subsystem
          default: '{subsystem}'
          description: "subsystem name"
      - string:
          name: parent_buildnum
          default: '1'
          description: "parent build number"

- wrapper:
    name: RCP_WRAPPERS
    wrappers: 
      - timeout:
          timeout: 90
          type: absolute
          fail: true
      - workspace-cleanup
      - timestamps

- trigger:
    name: RCP_TRIGGER
    triggers:
      - gerrit:
         trigger-on:
            - patchset-created-event
         projects:
            - project-compare-type: "PLAIN"
              project-pattern: '{scmurl}/{subsystem}'
              branches:
                 - branch-compare-type: 'PLAIN'
                   branch-pattern: 'cloud_controller_dev' 
- builder:
    name: COMPILE_builder
    builders:
      - shell: |
          git clone git@gitlab.china.nsn-net.net:platformci/sad-runner.git
          svn export https://svne1.access.nsn.com/isource/svnroot/citools/cctools/trunk/OPTcheckout/git_rcpco.sh
          ./git_rcpco.sh $subsystem $GERRIT_REFSPEC
          export V=c
          python $WORKSPACE/sad-runner/sad_runner.py -p rcp -m $subsystem -b $WORKSPACE/workspace/$subsystem -o $WORKSPACE/statistics

- builder:
    name: STATISTIC_builder
    builders:
      - shell: |
          git clone git@gitlab.china.nsn-net.net:platformci/sad-runner.git
          svn export https://svne1.access.nsn.com/isource/svnroot/citools/cctools/trunk/OPTcheckout/git_rcpco.sh
          ./git_rcpco.sh $subsystem $GERRIT_REFSPEC
          export V=s
          export PATH=$PATH:/apps/klocwork/bin
          python $WORKSPACE/sad-runner/sad_runner.py -p rcp -m $subsystem -b $WORKSPACE/workspace/$subsystem -o $WORKSPACE/statistics

- builder:
    name: UT_builder
    builders:
      - shell: |
          git clone git@gitlab.china.nsn-net.net:platformci/sad-runner.git
          svn export https://svne1.access.nsn.com/isource/svnroot/citools/cctools/trunk/OPTcheckout/git_rcpco.sh
          ./git_rcpco.sh $subsystem $GERRIT_REFSPEC
          cd $WORKSPACE/workspace
          svn co http://svne1.access.nsn.com/isource/svnroot/SS_ILThirdpart/branches/cloud_controller_dev/SS_ILThirdpart/
          export V=t
          #python $WORKSPACE/sad-runner/sad_runner.py -p rcp -m $subsystem -b $WORKSPACE/workspace/$subsystem -o $WORKSPACE/statistics
          $WORKSPACE/workspace/product/build/setcougarenv.sh -w -a x86 -j "cd $WORKSPACE/workspace/$subsystem/build;make ut"

- builder:
    name: UPLOAD_IMAGE_builder
    builders:
      - shell:
          !include-raw-escape uploadimage.sh
          
- builder:
    name: FT_builder
    builders:
      - shell:
          !include-raw rcpft.sh
          
- publisher:
    name: COMPILE_ARTIFACT
    publishers:
      - archive:
          artifacts: 'statistics/**'
      - scp:
          site: 'hzwebserver02.china.nsn-net.net'
          files:
             - target: 'tar/{subsystem}/$BUILD_NUMBER/'
               source: '**/*.tar.xz'
               copy-after-failure: true
- publisher:
    name: STATIC_ARTIFACT
    publishers:
      - archive:
          artifacts: 'statistics/**'
- publisher:
    name: UT_ARTIFACT
    publishers:
      - archive:
          artifacts: '**/lcov_report/**'
- publisher:
    name: FT-ARTIFACT
    publishers:
      - archive:
          artifacts: '**/logs/*,**/errlogs/*'               
- publisher:
    name: UPLOAD_IMAGE_ARTIFACT
    publishers:
      - archive:
          artifacts: '**/*installed_pkg-list'


